version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  payment-service:
    build: ../payment-service
    ports:
      - "5005:5005"
    env_file:
      - ../payment-service/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/paymentdb
      - PORT=5005
    depends_on:
      - mongo

volumes:
  mongo-data: