apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-login-service
  labels:
    app: driver-login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-login-service
  template:
    metadata:
      labels:
        app: driver-login-service
    spec:
      containers:
        - name: driver-login-service
          image: driver-login-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/logindb
            - name: PORT
              value: "5001"

---
apiVersion: v1
kind: Service
metadata:
  name: driver-login-service
spec:
  selector:
    app: driver-login-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP