apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-backend
  labels:
    app: restaurant-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-backend
  template:
    metadata:
      labels:
        app: restaurant-backend
    spec:
      containers:
        - name: restaurant-backend
          image: restaurant-backend:latest
          ports:
            - containerPort: 5002
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/restaurantdb
            - name: PORT
              value: "5002"

---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-backend
spec:
  selector:
    app: restaurant-backend
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP